### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are n ot supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol In jectable in C:/Users/.../.../.../.../.../.../node_modules/ngx-sweetalert2/node_module s/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in C:/Users/.../.../.../.../.../.../node_modules/ngx-sweetalert2/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in C:/Users/.../.../.../.../.../.../node_modules/ngx-sweetalert2/node_mod ules/@angular/core/src/di/opaque_token.d.ts  ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\...\...\...\...\...\...\src'  @ ./src/main.ts 3:0-74  @ multi ./src/main.ts

### ISSUE THREAD

**Issue by danielvaldebenito** [selcukkutuk/ngx-sweetalert2#1]
Hi.
I am trying to build angular app to production, and I get this error. Any idea about the problem? Thanks

**Comment by velusgautam** [comment]
I am also getting the same error for prod build

**Comment by velusgautam** [comment]
I directly now use sweetalert2 since it has typescript support.
you can use it like this in  your component.

import swal from 'sweetalert2';

and can call like below in constructor or anywhere 

swal({
  title: 'Error!',
  text: 'Do you want to continue',
  type: 'error',
  confirmButtonText: 'Cool'
})

**Comment by selcukkutuk** [comment]
First of all I apologize for writing late. I had a baby 10 days ago. I did not care for that. Now the problem is solved. Good coding.

**Comment by danielvaldebenito** [comment]
Sorry, I still have the problem. I am a new angular developer. How I can to solve it?

**Comment by velusgautam** [comment]
Thank you for your dedication and fast response. It happened due to old version of angular@core

**Comment by rajawat24** [comment]
@velusgautam if we use import swal from 'sweetalert2'; directly
so what are the use of this module. can we have any solution to fix with the ngx-sweetalert2. because i have use this module throughout the whole my application.
